

class UserFound(Exception):
    pass


class UserNotFound(Exception):
    pass
